In [3]:
import numpy as np

# input matrix (batches of inputs)
inputs = [[1, 2, 3, 2.5],
          [2.0 ,5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# weights of 1st hidden layer
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

# biases of 1st hidden layer
biases = [2, 3, 0.5]

# weights of 2nd hidden layer
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

# biases of 2nd hidden layer
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases  # becomes the input for 2nd hidden layer

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [8]:
# making Layer objects

import numpy as np
np.random.seed(0)

class Layer_Dense:
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

X = [[1, 2, 3, 2.5],
     [2.0 ,5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

layer_1 = Layer_Dense(4, 5)
layer_2 = Layer_Dense(5, 2)

layer_1.forward(X)
# print(layer_1.output)

layer_2.forward(layer_1.output)
print(layer_2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
